server:
port: 8080


spring:
datasource:
url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:thirdplace}
username: ${DB_USER:thirdplace}
password: ${DB_PASSWORD:thirdplace}
jpa:
hibernate:
ddl-auto: validate
properties:
hibernate:
dialect: org.hibernate.dialect.PostgreSQLDialect
format_sql: true
sql:
init:
mode: always


management:
endpoints:
web:
exposure:
include: health,info